language: node_js

node_js:
  - 4

before_install:
  - npm install -g npm@'2.x.x'

before_script:
  - npm install

script:
  - npm run ci

notifications:
  flowdock:
    secure: 2dD4hgJHA6zi5NxiPgYE+MPJDLK6TiHNReFkBSNpBxIvC7KTm7DZMD4UiqULcv55WjYQ2xCEWjuGjQr+vHxsMcCFb2/HxdshP+VHwDg+mZo+8LPH1ggy/C0oR0z8wTJazwl0b13ikwCykwBbMN+YTXX3/EIizf3hJq0gQLxn4pvSWxfrVQHPXqhqjbdTT02bMxDX54xk3ULkM6/8fxn68k7b+yk28dXpgz/glrdc/ed/pPQqphl9qOBlxIKh5LUiCwPcPzqCvyXuurMeMJTaizOq67l1JLxQ4f2NUf0dV66GxXksXYOv7KWSeb+oRYRh6v6Jcf5m1y5uyKHsJkPArUUcaI3xiwHL67K9NYAMZe7D1ZYL9TTLdaFy1HWkEZJuACd5wHrtHQI4oBm6xcZkAwo89r3QBDw15sLScrPqAASml9sqaS/wBPQNv5q9R3MI1KpmZHs9jwEdU3Vw+td4OitwbU5ocGMjXes94qvl/CBuZCjhfpMcGEKaWdc6NoGADkD4G4R/0JjpPpHcG2iztMtlCmvYohJqoVSgmyHxuW+frb/85noEHZummZd+HuS9QbUzOgBenvb9RT6UiuZRBVciQXAGBAGQgPV9vkZrQNDPzJ0vjI/syphAoYokwRhyeyWhj1XV5Kvw13PRnQLf9SLVxlZLv1yYJ1bK4sEj96k=
